# Generated by Django 5.2.1 on 2025-07-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_category_customer_product_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
