# Generated by Django 5.2.1 on 2025-07-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_category_options_product_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_code',
            new_name='code_no',
        ),
    ]
